In [1]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold

In [4]:
labels = pd.read_csv('/home/AZA/PycharmProjects/competitions/cvppa2023/dataset/WW2020/labels.csv')
clusters = pd.read_csv('/home/AZA/PycharmProjects/competitions/cvppa2023/dataset/WW2020/cluster_se101.csv')

In [12]:
df = pd.merge(left=labels, right=clusters, on='names')

In [32]:
df

                  names        labels  classes  fold  clusters
0        20200422_0.jpg     NPKCa+m+s        6     2         1
1        20200506_1.jpg          NPK_        0     0         8
2        20200325_4.jpg         NPKCa        3     0         5
3        20200422_5.jpg         NPKCa        3     3         3
4        20200506_7.jpg  unfertilized        4     4        19
...                 ...           ...      ...   ...       ...
1327  20200422_1795.jpg          NPK_        0     3        17
1328  20200325_1796.jpg  unfertilized        4     2        18
1329  20200506_1797.jpg  unfertilized        4     3        18
1330  20200325_1798.jpg         _PKCa        5     0         0
1331  20200325_1799.jpg         _PKCa        5     0        15

[1332 rows x 5 columns]

In [24]:
for i in df['clusters'].unique():
    dfc = df[df['clusters']==i]
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    fold = 0
    for train_index, test_index in skf.split(dfc, dfc['labels']):
        df.loc[dfc.index[test_index], 'fold'] = fold
        fold += 1

/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/home/AZA/PycharmProjects/competitions/cvppa2023/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:725: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

In [35]:
for i in df['fold'].unique():
    dfc = df[df['fold']==i]
    print(dfc['classes'].value_counts())

classes
3    41
4    39
2    38
6    37
1    37
5    37
0    36
Name: count, dtype: int64
classes
4    41
0    40
6    40
3    39
1    39
2    39
5    37
Name: count, dtype: int64
classes
3    39
1    39
6    39
0    38
2    38
4    35
5    35
Name: count, dtype: int64
classes
2    41
0    39
4    37
1    37
3    36
6    36
5    35
Name: count, dtype: int64
classes
4    40
6    40
1    40
0    39
3    37
5    36
2    36
Name: count, dtype: int64

In [33]:
df.to_csv("dataset/WW2020/labels_cluster_split.csv")

In [28]:
import numpy as np
misslabels = np.loadtxt('dataset/WW2020/baseline/names_misslabels.txt', dtype=str)

In [31]:
df[~df['names'].isin(misslabels)]

                  names        labels  classes  fold  clusters
0        20200422_0.jpg     NPKCa+m+s        6     2         1
2        20200325_4.jpg         NPKCa        3     0         5
3        20200422_5.jpg         NPKCa        3     3         3
4        20200506_7.jpg  unfertilized        4     4        19
5        20200506_8.jpg          NPK_        0     2         6
...                 ...           ...      ...   ...       ...
1327  20200422_1795.jpg          NPK_        0     3        17
1328  20200325_1796.jpg  unfertilized        4     2        18
1329  20200506_1797.jpg  unfertilized        4     3        18
1330  20200325_1798.jpg         _PKCa        5     0         0
1331  20200325_1799.jpg         _PKCa        5     0        15

[1011 rows x 5 columns]